# Generated by Django 4.2.11 on 2024-05-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_camp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='season',
            field=models.CharField(choices=[('Hiver', 'Hiver'), ('Printemps', 'Printemps'), ('Eté', 'Ete'), ('Automne', 'Automne'), ("Toute l'année", 'All')], default="Toute l'année", max_length=20, verbose_name='Saison'),
        ),
    ]
