# Generated by Django 4.2.11 on 2024-05-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_ingredient_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeXEngridient',
            new_name='RecipeXEngredient',
        ),
    ]
