# Generated by Django 4.2.11 on 2024-05-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_recipexengridient_recipexengredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipexengredient',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Quantité'),
        ),
    ]
