# Generated by Django 4.2.11 on 2024-05-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_tag_parent_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='season',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='season',
            field=models.ManyToManyField(to='database.season'),
        ),
    ]
