# Generated by Django 4.2.11 on 2024-05-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_season_remove_recipe_avg_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ManyToManyField(to='database.category'),
        ),
    ]
