# Generated by Django 4.2.11 on 2024-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipexengredient',
            name='age',
            field=models.CharField(choices=[('18+', 'Default'), ('Petit F', 'Pf'), ('Petit G', 'Pg'), ('Grand F', 'Gf'), ('Grand G', 'Gg')], default='18+', max_length=10, verbose_name="Tranche d'âge"),
        ),
        migrations.AlterField(
            model_name='section',
            name='age',
            field=models.CharField(choices=[('18+', 'Default'), ('Petit F', 'Pf'), ('Petit G', 'Pg'), ('Grand F', 'Gf'), ('Grand G', 'Gg')], default='18+', max_length=10, verbose_name="Tranche d'âge"),
        ),
    ]
