# Generated by Django 4.2.11 on 2024-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_recipexengredient_age_alter_section_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='type',
            field=models.CharField(choices=[('Menu', 'Menu'), ('Camp', 'Camp')], default='Camp', max_length=10, verbose_name='Type'),
        ),
    ]
