# Generated by Django 4.2.11 on 2024-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_remove_recipe_tags_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='vege',
            field=models.BooleanField(default=False, verbose_name='Vege ?'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='mesurement',
            field=models.CharField(choices=[('KG', 'Kg'), ('L', 'L'), ('PIECE', 'Piece'), ('TRANCHE', 'Tranche'), ('CONDIMENT', 'Condiment')], default='KG', max_length=10, verbose_name='Mesure'),
        ),
    ]
