# Generated by Django 4.2.11 on 2024-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_ingredient_vege_alter_ingredient_mesurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Prix moyen'),
        ),
    ]
