# Generated by Django 4.2.11 on 2024-05-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_menu_moment_alter_menu_nbr_anim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientxsu',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True, verbose_name='Quantité'),
        ),
    ]
