# Generated by Django 4.2.11 on 2024-05-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_ingredientxsu_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientxsu',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5, verbose_name='Quantité'),
        ),
    ]
