# Generated by Django 4.2.11 on 2024-05-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_alter_ingredientxsu_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientxsu',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='database.category'),
        ),
    ]
