# Generated by Django 4.2.11 on 2024-05-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nom'),
        ),
    ]
