# Generated by Django 4.2.11 on 2024-05-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_remove_ingredient_category_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipexengredient',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité'),
        ),
    ]
