# Generated by Django 4.2.11 on 2024-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_alter_recipexengredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='vege',
        ),
        migrations.AddField(
            model_name='recipexengredient',
            name='vege',
            field=models.BooleanField(default=False, verbose_name='Vege ?'),
        ),
    ]
