# Generated by Django 4.2.11 on 2024-05-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_alter_address_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=10, verbose_name='Pays'),
        ),
    ]
