# Generated by Django 4.2.11 on 2024-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=15, verbose_name='Pays'),
        ),
    ]
