# Generated by Django 4.2.11 on 2024-06-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='status',
            field=models.CharField(choices=[('En Cours', 'C'), ('Fini', 'F'), ('Pas commencé', 'N'), ('Hidden', 'H')], default='En Cours', max_length=20, verbose_name='Status'),
        ),
    ]
