# Generated by Django 4.2.11 on 2024-06-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_alter_menu_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='recipe_name',
            field=models.CharField(default='', max_length=300, verbose_name='recipe_name'),
        ),
    ]
