# Generated by Django 4.2.11 on 2024-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_menu_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientxsu',
            name='category',
            field=models.CharField(default='', max_length=300, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='ingredientxsu',
            name='ingredient',
            field=models.CharField(default='', max_length=300, verbose_name='ingredient_name'),
        ),
    ]
