# Generated by Django 4.2.11 on 2024-06-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_alter_ingredientxsu_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientxsu',
            name='mesurement',
            field=models.CharField(choices=[('KG', 'Kg'), ('L', 'L'), ('PIECE', 'Piece'), ('TRANCHE', 'Tranche'), ('CONDIMENT', 'Condiment')], default='KG', max_length=10, verbose_name='Mesure'),
        ),
    ]
