# Generated by Django 4.2.11 on 2024-06-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_ingredientxsu_mesurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nom')),
                ('category', models.ManyToManyField(to='database.category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='database.address')),
            ],
        ),
    ]
