# Generated by Django 4.2.11 on 2024-06-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_producteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
