# Generated by Django 4.2.11 on 2024-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_alter_producteur_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='mesurement',
            field=models.CharField(choices=[('KG', 'Kg'), ('L', 'L'), ('PIECE', 'Piece'), ('TRANCHE', 'Tranche'), ('CONDIMENT', 'Condiment')], default='KG', max_length=10, verbose_name='Mesure'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ingredient',
            field=models.CharField(default='', max_length=150, verbose_name='ingredient_name'),
        ),
    ]
